eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer-1-server.com:8762/eureka/,http://peer-3-server.com:8764/eureka/,http://peer-2-server.com:8763/eureka/,http://localhost:8761/
  
logging:
  level:
    root: DEBUG
    
